find_glob_dirs is now pm_find_glob_pkgs.
The name change reflect the coherence that we are using pkg names.
Those names reflects a dir in pdb, if portmaster was used to build that pkg.

diff --git a/portmaster b/portmaster
--- a/portmaster
+++ b/portmaster
@@ -331,6 +331,43 @@ pm_sv             () { [ -n "$PM_SU_VERBOSE" ] && echo -e "===>>> SU $*"; }
 # string manipulation functions
 pm_globstrip () { local in ; in=${1%[*]} ; in=${in%\\} ; echo $in ; }
 
+# Takes a pattern as input; return values
+# 0 - Matched one and only one directory in $pdb
+# 1 - No match
+# 2 - Matched multiple directories
+pm_find_glob_pkgs () {
+	# Global glob_pkgs
+	local pattern num
+	pattern="$(pm_globstrip $1)"
+	num=$(pkg info -g ${pattern}\* | wc -l)
+	glob_pkgs="$(pkg query -g "%n-%v" ${pattern}\*)"
+	case $num in
+	0) unset glob_pkgs; return 1 ;;
+	1) return 0 ;;
+	*) return 2 ;;
+	esac
+}
+
+origin_from_pdb () {
+	local o
+
+	pkg query '%o' $1 2>/dev/null && return 0
+
+	# Old perl package relics, probably
+	case "$1" in bsdpan-*) return 3 ;; esac
+
+	echo "	===>>> No origin available for $1" >&2
+	echo '' >&2
+	if pkg info -e $1 ; then
+		if [ -e "$pdb/$1/+IGNOREME" ]; then
+			echo "  ===>>> $pdb/$1/+IGNOREME exists" >&2
+		fi
+		return 2
+	else
+		return 1
+	fi
+}
+
 #=============== Initialization of ports variables [ parent ] ===============
 # pd (ports dir); pdb (pkg db dir); port_dbdir (port configuration)
 if [ "$$" -eq "$PM_PARENT_PID" ]; then
@@ -515,49 +552,6 @@ usage () {
 	pm_safe_exit ${1:-1}
 }
 
-# Takes a pattern as input
-# Return values:
-# 0 - Matched one and only one directory in $pdb
-# 1 - No match
-# 2 - Matched multiple directories
-find_glob_dirs () {
-	# Global: glob_dirs
-	local pattern
-
-	pattern=`pm_globstrip $1`
-	glob_dirs=`pkg query -g "%n-%v" ${pattern}\*`
-	case "$glob_dirs" in
-	# Match a newline in multiple responses from find
-	*'
-'*)		return 2 ;;
-	'')	;;
-	*)	return ;;
-	esac
-
-	unset glob_dirs
-	return 1
-}
-
-origin_from_pdb () {
-	local o
-
-	pkg query '%o' $1 2>/dev/null && return 0
-
-	# Old perl package relics, probably
-	case "$1" in bsdpan-*) return 3 ;; esac
-
-	echo "	===>>> No origin available for $1" >&2
-	echo '' >&2
-	if pkg info -e $1 ; then
-		if [ -e "$pdb/$1/+IGNOREME" ]; then
-			echo "  ===>>> $pdb/$1/+IGNOREME exists" >&2
-		fi
-		return 2
-	else
-		return 1
-	fi
-}
-
 #=============== Begin Command Line Option Processing ===============
 
 packages_init () {
@@ -690,18 +684,18 @@ while getopts 'BCDFGHKLPRabde:fghilm:nop:r:stvwx:y' COMMAND_LINE_ARGUMENT ; do
 	p)	fail 'The -p option has been deprecated' ;;
 	r)	PM_URB=ropt
 		if [ -d "$pdb/$OPTARG" ] && ( pkg info -e $OPTARG ); then
-			glob_dirs=$OPTARG
+			glob_pkgs=$OPTARG
 		else
 			case "$OPTARG" in */*) fail 'The argument to -r must be a package name, or a glob pattern' ;; esac
-			find_glob_dirs $OPTARG
+			pm_find_glob_pkgs $OPTARG
 			case $? in
 			1)	fail "$OPTARG is not installed" ;;
 			2)	fail 'The argument to -r must match only one port' ;;
 			esac
 		fi
-		PM_URB_IPORTS="${PM_URB_IPORTS}${glob_dirs##*/} "
-		PM_URB_ORIGINS="${PM_URB_ORIGINS}`origin_from_pdb ${glob_dirs##*/}` "
-		unset glob_dirs ;;
+		PM_URB_IPORTS="${PM_URB_IPORTS}${glob_pkgs##*/} "
+		PM_URB_ORIGINS="${PM_URB_ORIGINS}`origin_from_pdb ${glob_pkgs##*/}` "
+		unset glob_pkgs ;;
 	s)	CLEAN_STALE=sopt ;;
 	t)	PM_THOROUGH=topt; ARGS="-t $ARGS" ;;
 	v)	PM_VERBOSE=vopt; ARGS="-v $ARGS" ;;
@@ -1897,13 +1891,13 @@ fi
 
 if [ -n "$EXPUNGE" ]; then
 	if [ ! -d "$pdb/$EXPUNGE" ] || ( ! pkg info -e $EXPUNGE ); then
-		find_glob_dirs $EXPUNGE
+		pm_find_glob_pkgs $EXPUNGE
 		case $? in
 		1)	fail "No such port: $EXPUNGE" ;;
 		2)	echo "===>>> $EXPUNGE matched multiple ports"
 			fail "The -e option works with only one port at a time" ;;
-		0)	EXPUNGE=${glob_dirs#$pdb/}
-			unset glob_dirs ;;
+		0)	EXPUNGE=${glob_pkgs#$pdb/}
+			unset glob_pkgs ;;
 		esac
 	fi
 
@@ -2575,16 +2569,16 @@ multiport () {
 		*)	if [ -d "$pdb/$port" ] && ( pkg info -e $port ); then
 				worklist_temp="$worklist_temp $port"
 			else
-				find_glob_dirs $port
+				pm_find_glob_pkgs $port
 				case $? in
 				1)	fail "$port is not installed"
 					;;
 				*)	local dir
-					for dir in $glob_dirs; do
+					for dir in $glob_pkgs; do
 					worklist_temp="$worklist_temp ${dir#$pdb/}"
 					done ;;
 				esac
-				unset glob_dirs
+				unset glob_pkgs
 			fi ;;
 		esac
 	done
@@ -2938,13 +2932,13 @@ if [ -z "$REPLACE_ORIGIN" ]; then
 	esac
 
 	if [ -z "$portdir" -a -z "$upg_port" ]; then
-		find_glob_dirs $argv
+		pm_find_glob_pkgs $argv
 		case $? in
 		1)	echo '' ; no_valid_port ;;
-		2)	multiport $glob_dirs ;;
-		0)	upg_port=${glob_dirs#$pdb/} ;;
+		2)	multiport $glob_pkgs ;;
+		0)	upg_port=${glob_pkgs#$pdb/} ;;
 		esac
-		unset glob_dirs
+		unset glob_pkgs
 	fi
 	unset argv
 else
@@ -2970,8 +2964,8 @@ else
 	*)	if [ -d "$pdb/$arg2" ] && ( pkg info -e $arg2 ); then
 			ro_upg_port=$arg2
 		else
-			find_glob_dirs $arg2 && ro_upg_port=${glob_dirs#$pdb/}
-			unset glob_dirs
+			pm_find_glob_pkgs $arg2 && ro_upg_port=${glob_pkgs#$pdb/}
+			unset glob_pkgs
 		fi
 		if [ -n "$ro_upg_port" ]; then
 			ro_opd=`origin_from_pdb $ro_upg_port`
